# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antiparasitario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de aplicacion')),
                ('vermifugos', models.CharField(max_length=20)),
                ('proxima_aplicacion', models.DateField(verbose_name='Proxima aplicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha', models.DateField(verbose_name='Fecha de Deteccion')),
                ('tratamiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombre', models.CharField(max_length=30)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_de_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('pelaje', models.CharField(max_length=15)),
                ('foto', models.ImageField(upload_to='mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario_nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha de vacunacion')),
                ('descripcion', models.CharField(max_length=30)),
                ('proxima_vacuna', models.DateField(verbose_name='fecha de proxima vacunacion')),
                ('veterinario', models.CharField(max_length=30)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalchic.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalchic.Propietario'),
        ),
        migrations.AddField(
            model_name='enfermedad',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalchic.Paciente'),
        ),
        migrations.AddField(
            model_name='antiparasitario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animalchic.Paciente'),
        ),
    ]
