# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='archivo',
            field=models.FileField(default=None, upload_to='pet_enfermedades/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(upload_to='pet_images/'),
        ),
    ]
