# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0002_auto_20170225_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='archivo',
            field=models.FileField(upload_to='pet_enfermedades/'),
        ),
    ]
