# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0004_remove_enfermedad_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='enfermedad_archivo',
            field=models.FileField(blank=True, upload_to='enfermedades_archivos/'),
        ),
    ]
