# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0005_enfermedad_enfermedad_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='enfermedad_archivo',
            field=models.FileField(upload_to='enfermedades_archivos/'),
        ),
    ]
