# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0006_auto_20170227_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermedad',
            name='enfermedad_archivo',
            field=models.FileField(blank=True, upload_to='enfermedades_archivos/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pet_images/'),
        ),
    ]
