# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animalchic', '0007_auto_20170301_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
