# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animalchic', '0009_auto_20170306_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
